package com.example.myengquiz01

object GameConstants {
    val words = listOf(
        "Daddy",
        "Mommy",
        "Registration",
        "American",
        "Adorable",
        "Angle",
        "Answer",
        "Duck",
        "Human",
        "Table",
        "Murder",
        "Dead",
        "Hungry",
        "Chair",
        "Sexy",
        "Bill",
        "Busy",
        "working",
        "Wisdom",
        "Banana",
        "Belgium",
        "Bell",
        "Ben",
        "Ali",
        "Port/Dickson",
        "Bathroom",
        "Apartment",
        "Home",
        "Shower",
        "Brazil",
        "Indian",
        "Brunei",
        "Bulgaria",
        "Burkina/Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape",
        "Islands",
        "Central",
        "Chad",
        "Chile",
        "China",

        )
}